### PR TITLE
Revamp git cards design

### PR DESCRIPTION
**Pull request by vijayranghar**

### CODE REVIEW

**Comment by vijayranghar** [comment]
screencapture-localhost-3000-2019-10-02-01_18_00

**Comment by vijayranghar** [comment]
Lol, didn't realize someone else is working on rating also. If, it looks fine will resolve conflicts
👍

**Comment by vijayranghar** [comment]
chrome-capture

**Comment by antonybudianto** [comment]
Hi @vijayranghar , Thanks for the PR!
Recently I just pushed new design to `master` so you need to resolve the conflict first. 
One feedback is the rating system looks like most of the dev have less stars.. So I suggest to drop the rating for now. I've plan to query the total stars for each dev, so we'll use that instead.

**Comment by vijayranghar** [comment]
image

**Comment by antonybudianto** [comment]
Hi, I think we can leave the card design as it is in master branch, while we can use the hover style

**Comment by vijayranghar** [comment]
image

**Comment by antonybudianto** [comment]
Cool, will review after worktime

**Comment by antonybudianto** [comment]
Thank you @vijayranghar 🎉

**Pull request merged**
