### PR TITLE
Enhancement Link User

### PR DESCRIPTION
**Pull request by adibfirman**
I think to make some eye-catching in navigation github profile it feels like better 😎️
ezgif com-video-to-gif

### CODE REVIEW

**Comment by antonybudianto** [comment]
Hi, thanks for PR!
I think text-decoration should not be `none` https://webaim.org/techniques/hypertext/link_text

**Comment by adibfirman** [comment]
Good to know, thanks
after reading that article, and i just adding selector `:focus` too

> Hi, thanks for PR!
> I think text-decoration should not be `none` https://webaim.org/techniques/hypertext/link_text

**Comment by antonybudianto** [comment]
Please help sending the latest GIF 😄

**Comment by adibfirman** [comment]
FYI: it's hard to me upload a gif, cus in ubuntu, you must record a desktop and convert it to gif hahaha, but don't worry about that
ezgif com-video-to-gif (1)

**Comment by antonybudianto** [comment]
LGTM, thank you 😊

**Pull request merged**
